name: 3d contribution graph

"on":
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Varunbp06
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh 3d graph [skip ci]"
          file_pattern: "profile-3d/*"
